version: "3"

services:
  wwdatabase-db:
    container_name: wwdatabase-db
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5445:5432"

  wwdatabase:
    depends_on:
      - wwdatabase-db
    image: cod3rcarl/wwdatabase
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "50052:50050"
volumes:
  database-data:
